
package:
  name: nadetector
  version: 0.0.3

source:
  path: .. #tells conda-build that the source code is in the parent directory.

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{environ['GIT_DESCRIBE_HASH']}}
  entry_points:
    - nadetector = nadetector.__main__:main   # We must have an entry point specified for each entry point in setup.py or the noarch conda build will fail.

requirements:
  build:
    - python
    - setuptools

  run:
    - pyqt
    - scikit-image
    - pywin32

app:
  entry: nadetector
  summary: PWS NA Calibration GUI
  type: desk
  own_environment: False

about:
  home: https://github.com/nanthony21/NA-Detector
  summary: "A GUI for measuring the NA of a microscope with a bertrand telescope."
  description: "A GUI for measuring the NA of a microscope with a bertrand telescope."
  dev_url: https://github.com/nanthony21/NA-Detector

